service: streamlit-frontend-new
runtime: custom
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

runtime_config:
  python_version: 3.8

entrypoint: gunicorn -b :8080 main:app
